from PyQt4 import QtCore, QtGui
import time

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Telebix(object):
    def setupUi(self, Telebix):
        Telebix.setObjectName(_fromUtf8("Telebix"))
        Telebix.setFixedSize(374, 404)
        Telebix.center()
        Telebix.setWindowIcon(QtGui.QIcon('resources/icon.png'))
        Telebix.setWindowFlags(Telebix.windowFlags() & ~QtCore.Qt.WindowMinMaxButtonsHint)
        self.tabWidget = QtGui.QTabWidget(Telebix)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 374, 404))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.start_button = QtGui.QPushButton(self.tab)
        self.start_button.setGeometry(QtCore.QRect(70, 320, 97, 26))
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.stop_button = QtGui.QPushButton(self.tab)
        self.stop_button.setGeometry(QtCore.QRect(190, 320, 97, 26))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.label_status = QtGui.QLabel(self.tab)
        self.label_status.setGeometry(QtCore.QRect(210, 350, 61, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.status = QtGui.QLabel(self.tab)
        self.status.setGeometry(QtCore.QRect(265, 350, 91, 17))
        self.status.setText(_fromUtf8(""))
        self.status.setObjectName(_fromUtf8("status"))
        self.infohosts = QtGui.QCheckBox(self.tab)
        self.infohosts.setGeometry(QtCore.QRect(30, 140, 171, 22))
        self.infohosts.setObjectName(_fromUtf8("infohosts"))
        self.infographs = QtGui.QCheckBox(self.tab)
        self.infographs.setGeometry(QtCore.QRect(30, 260, 161, 22))
        self.infographs.setObjectName(_fromUtf8("infographs"))
        self.infozabbix = QtGui.QCheckBox(self.tab)
        self.infozabbix.setGeometry(QtCore.QRect(30, 200, 171, 22))
        self.infozabbix.setObjectName(_fromUtf8("infozabbix"))
        self.infonotifications = QtGui.QCheckBox(self.tab)
        self.infonotifications.setGeometry(QtCore.QRect(30, 110, 171, 22))
        self.infonotifications.setObjectName(_fromUtf8("infonotifications"))
        self.infowebs = QtGui.QCheckBox(self.tab)
        self.infowebs.setGeometry(QtCore.QRect(30, 230, 171, 22))
        self.infowebs.setObjectName(_fromUtf8("infowebs"))
        self.infousers = QtGui.QCheckBox(self.tab)
        self.infousers.setGeometry(QtCore.QRect(30, 170, 171, 22))
        self.infousers.setObjectName(_fromUtf8("infousers"))
        self.infoevents = QtGui.QCheckBox(self.tab)
        self.infoevents.setGeometry(QtCore.QRect(30, 290, 171, 22))
        self.infoevents.setObjectName(_fromUtf8("infoevents"))
        self.logo = QtGui.QLabel(self.tab)
        self.logo.setGeometry(QtCore.QRect(2, 0, 371, 108))
        self.logo.setText(_fromUtf8(""))
        self.logo.setObjectName(_fromUtf8("logo"))
        self.logo.setStyleSheet("background-image: url(resources/telebix.png)")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 361, 171))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.bot_token = QtGui.QLineEdit(self.groupBox)
        self.bot_token.setGeometry(QtCore.QRect(100, 36, 141, 27))
        self.bot_token.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bot_token.setText(_fromUtf8(""))
        self.bot_token.setMaxLength(45)
        self.bot_token.setEchoMode(QtGui.QLineEdit.Password)
        self.bot_token.setObjectName(_fromUtf8("bot_token"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.get_id = QtGui.QPushButton(self.groupBox)
        self.get_id.setGeometry(QtCore.QRect(250, 36, 97, 26))
        self.get_id.setObjectName(_fromUtf8("get_id"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 81, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.save_telegram = QtGui.QPushButton(self.groupBox)
        self.save_telegram.setGeometry(QtCore.QRect(250, 86, 97, 26))
        self.save_telegram.setObjectName(_fromUtf8("save_telegram"))
        self.connect_test_telegram = QtGui.QLabel(self.groupBox)
        self.connect_test_telegram.setGeometry(QtCore.QRect(235, 110, 131, 20))
        self.connect_test_telegram.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.connect_test_telegram.setText(_fromUtf8(""))
        self.connect_test_telegram.setAlignment(QtCore.Qt.AlignCenter)
        self.connect_test_telegram.setObjectName(_fromUtf8("connect_test_telegram"))
        self.user_id = QtGui.QLineEdit(self.groupBox)
        self.user_id.setGeometry(QtCore.QRect(80, 85, 161, 27))
        self.user_id.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.user_id.setText(_fromUtf8(""))
        self.user_id.setEchoMode(QtGui.QLineEdit.Normal)
        self.user_id.setObjectName(_fromUtf8("user_id"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 180, 361, 171))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 81, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 81, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.zabbix_host = QtGui.QLineEdit(self.groupBox_2)
        self.zabbix_host.setGeometry(QtCore.QRect(50, 36, 161, 27))
        self.zabbix_host.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.zabbix_host.setText(_fromUtf8(""))
        self.zabbix_host.setEchoMode(QtGui.QLineEdit.Normal)
        self.zabbix_host.setObjectName(_fromUtf8("zabbix_host"))
        self.zabbix_user = QtGui.QLineEdit(self.groupBox_2)
        self.zabbix_user.setGeometry(QtCore.QRect(50, 86, 161, 27))
        self.zabbix_user.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.zabbix_user.setText(_fromUtf8(""))
        self.zabbix_user.setEchoMode(QtGui.QLineEdit.Normal)
        self.zabbix_user.setObjectName(_fromUtf8("zabbix_user"))
        self.zabbix_pass = QtGui.QLineEdit(self.groupBox_2)
        self.zabbix_pass.setGeometry(QtCore.QRect(50, 136, 161, 27))
        self.zabbix_pass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.zabbix_pass.setText(_fromUtf8(""))
        self.zabbix_pass.setEchoMode(QtGui.QLineEdit.Password)
        self.zabbix_pass.setObjectName(_fromUtf8("zabbix_pass"))
        self.save_zabbix = QtGui.QPushButton(self.groupBox_2)
        self.save_zabbix.setGeometry(QtCore.QRect(240, 86, 97, 26))
        self.save_zabbix.setObjectName(_fromUtf8("save_zabbix"))
        self.connect_test = QtGui.QLabel(self.groupBox_2)
        self.connect_test.setGeometry(QtCore.QRect(226, 115, 130, 17))
        self.connect_test.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.connect_test.setText(_fromUtf8(""))
        self.connect_test.setAlignment(QtCore.Qt.AlignCenter)
        self.connect_test.setObjectName(_fromUtf8("connect_test"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.command_label = QtGui.QLabel(self.tab_4)
        self.command_label.setGeometry(QtCore.QRect(135, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.command_label.setFont(font)
        self.command_label.setObjectName(_fromUtf8("command_label"))
        self.commands_label = QtGui.QLabel(self.tab_4)
        self.commands_label.setGeometry(QtCore.QRect(20, 260, 331, 16))
        self.commands_label.setObjectName(_fromUtf8("commands_label"))
        self.status_label = QtGui.QLabel(self.tab_4)
        self.status_label.setGeometry(QtCore.QRect(20, 200, 331, 16))
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.events_label = QtGui.QLabel(self.tab_4)
        self.events_label.setGeometry(QtCore.QRect(20, 230, 331, 16))
        self.events_label.setObjectName(_fromUtf8("events_label"))
        self.webs_label = QtGui.QLabel(self.tab_4)
        self.webs_label.setGeometry(QtCore.QRect(20, 170, 331, 16))
        self.webs_label.setObjectName(_fromUtf8("webs_label"))
        self.users_label = QtGui.QLabel(self.tab_4)
        self.users_label.setGeometry(QtCore.QRect(20, 320, 331, 16))
        self.users_label.setObjectName(_fromUtf8("users_label"))
        self.hosts_label = QtGui.QLabel(self.tab_4)
        self.hosts_label.setGeometry(QtCore.QRect(20, 290, 331, 16))
        self.hosts_label.setObjectName(_fromUtf8("hosts_label"))
        self.graphs_label = QtGui.QLabel(self.tab_4)
        self.graphs_label.setGeometry(QtCore.QRect(20, 140, 331, 16))
        self.graphs_label.setObjectName(_fromUtf8("graphs_label"))
        self.readmore_label = QtGui.QLabel(self.tab_4)
        self.readmore_label.setGeometry(QtCore.QRect(200, 340, 161, 20))
        self.readmore_label.setAlignment(QtCore.Qt.AlignCenter)
        self.readmore_label.setObjectName(_fromUtf8("readmore_label"))
        self.readmore_label.setOpenExternalLinks(True)
        self.howtouse_label = QtGui.QLabel(self.tab_4)
        self.howtouse_label.setGeometry(QtCore.QRect(133, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.howtouse_label.setFont(font)
        self.howtouse_label.setObjectName(_fromUtf8("howtouse_label"))
        self.howtouse2_label = QtGui.QLabel(self.tab_4)
        self.howtouse2_label.setGeometry(QtCore.QRect(20, 60, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.howtouse2_label.setFont(font)
        self.howtouse2_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.howtouse2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.howtouse2_label.setWordWrap(False)
        self.howtouse2_label.setObjectName(_fromUtf8("howtouse2_label"))
        self.howtouse1_label = QtGui.QLabel(self.tab_4)
        self.howtouse1_label.setGeometry(QtCore.QRect(20, 40, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.howtouse1_label.setFont(font)
        self.howtouse1_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.howtouse1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.howtouse1_label.setWordWrap(False)
        self.howtouse1_label.setObjectName(_fromUtf8("howtouse1_label"))
        self.howtouse1_label.linkActivated.connect(self.link)

        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.img_about = QtGui.QLabel(self.tab_3)
        self.img_about.setGeometry(QtCore.QRect(2, 0, 371, 108))
        self.img_about.setText(_fromUtf8(""))
        self.img_about.setObjectName(_fromUtf8("img_about"))
        self.img_about.setStyleSheet("background-image: url(resources/telebix.png)")
        self.contact = QtGui.QLabel(self.tab_3)
        self.contact.setGeometry(QtCore.QRect(35, 140, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.contact.setFont(font)
        self.contact.setObjectName(_fromUtf8("contact"))
        self.contact_1 = QtGui.QLabel(self.tab_3)
        self.contact_1.setGeometry(QtCore.QRect(95, 180, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.contact_1.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_1.setFont(font)
        self.contact_1.setObjectName(_fromUtf8("contact_1"))
        self.contact_email1 = QtGui.QLabel(self.tab_3)
        self.contact_email1.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_email1.setGeometry(QtCore.QRect(80, 200, 191, 20))
        self.contact_email1.setObjectName(_fromUtf8("contact_email1"))
        self.license = QtGui.QLabel(self.tab_3)
        self.license.setGeometry(QtCore.QRect(35, 290, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.license.setFont(font)
        self.license.setObjectName(_fromUtf8("license"))
        self.gnu_license = QtGui.QLabel(self.tab_3)
        self.gnu_license.setAlignment(QtCore.Qt.AlignCenter)
        self.gnu_license.setGeometry(QtCore.QRect(70, 330, 221, 20))
        self.gnu_license.setObjectName(_fromUtf8("gnu_license"))
        self.gnu_license.setOpenExternalLinks(True)
        self.contact_2 = QtGui.QLabel(self.tab_3)
        self.contact_2.setGeometry(QtCore.QRect(75, 230, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.contact_2.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_2.setFont(font)
        self.contact_2.setObjectName(_fromUtf8("contact_2"))
        self.contact_email2 = QtGui.QLabel(self.tab_3)
        self.contact_email2.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_email2.setGeometry(QtCore.QRect(85, 250, 181, 20))
        self.contact_email2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.contact_email2.setAutoFillBackground(False)
        self.contact_email2.setObjectName(_fromUtf8("contact_email2"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.retranslateUi(Telebix)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Telebix)
        self.createActions()
        self.createTrayIcon()
        self.trayIcon.setIcon(QtGui.QIcon('resources/telebix_mini.png'))
        self.trayIcon.activated.connect(self.iconActivated)
        self.trayIcon.show()

    def link(self):
    
        self.formLicense = License()
        self.formLicense.show()


    def center(self):

        qr = self.frameGeometry()
        cp = QtGui.QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())

    def closeEvent(self, event):
        if self.trayIcon.isVisible():
            QtGui.QMessageBox.information(self, "Telebix",
                                          "The program will keep running in the system tray. To "
                                          "terminate the program, choose <b>Quit</b> in the "
                                          "menu of the system tray entry.")
            self.hide()
            event.ignore()


    def iconActivated(self, reason):
        if reason in (QtGui.QSystemTrayIcon.Trigger, QtGui.QSystemTrayIcon.DoubleClick):
            self.iconComboBox.setCurrentIndex(
                (self.iconComboBox.currentIndex() + 1)
                % self.iconComboBox.count())
        elif reason == QtGui.QSystemTrayIcon.MiddleClick:
            self.showMessage()


    def showMessage(self):
        icon = QtGui.QSystemTrayIcon.MessageIcon(
            self.typeComboBox.itemData(self.typeComboBox.currentIndex()))
        self.trayIcon.showMessage(self.titleEdit.text(),
                                  self.bodyEdit.toPlainText(), icon,
                                  self.durationSpinBox.value() * 1000)


    def createActions(self):
        self.minimizeAction = QtGui.QAction("&Minimize", self,
                                            triggered=self.hide)

        self.restoreAction = QtGui.QAction("&Restore", self,
                                           triggered=self.show)

        self.quitAction = QtGui.QAction("&Quit", self,
                                        triggered=QtGui.qApp.quit)


    def createTrayIcon(self):
        self.trayIconMenu = QtGui.QMenu(self)
        self.trayIconMenu.addAction(self.minimizeAction)
        self.trayIconMenu.addAction(self.restoreAction)
        self.trayIconMenu.addSeparator()
        self.trayIconMenu.addAction(self.quitAction)
        self.trayIcon = QtGui.QSystemTrayIcon(self)
        self.trayIcon.setContextMenu(self.trayIconMenu)


    def retranslateUi(self, Telebix):
        Telebix.setWindowTitle(_translate("Telebix", "Telebix", None))
        self.start_button.setText(_translate("Telebix", "Start", None))
        self.stop_button.setText(_translate("Telebix", "Stop", None))
        self.label_status.setText(_translate("Telebix", "Status:", None))
        self.infohosts.setText(_translate("Telebix", "Information of hosts", None))
        self.infographs.setText(_translate("Telebix", "General Graphs", None))
        self.infozabbix.setText(_translate("Telebix", "Status of zabbix", None))
        self.infonotifications.setText(_translate("Telebix", "Realtime notification", None))
        self.infowebs.setText(_translate("Telebix", "Web monitoring", None))
        self.infousers.setText(_translate("Telebix", "Information of users", None))
        self.infoevents.setText(_translate("Telebix", "Last Events", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Telebix", "Home", None))
        self.groupBox.setTitle(_translate("Telebix", "Telegram Settings", None))
        self.label.setText(_translate("Telebix", "Bot Token:", None))
        self.get_id.setText(_translate("Telebix", "Get ID", None))
        self.label_2.setText(_translate("Telebix", "Your ID:", None))
        self.save_telegram.setText(_translate("Telebix", "Save", None))
        self.groupBox_2.setTitle(_translate("Telebix", "Zabbix Settings", None))
        self.command_label.setText(_translate("Telebix", "Help", None))
        self.commands_label.setText(_translate("Telebix", "/help - Help and information", None))
        self.status_label.setText(_translate("Telebix", "/status - List status of zabbix", None))
        self.events_label.setText(_translate("Telebix", "/events - List last five events", None))
        self.webs_label.setText(_translate("Telebix", "/webs - List monitored web scenarios", None))
        self.users_label.setText(_translate("Telebix", "/users - List users", None))
        self.hosts_label.setText(_translate("Telebix", "/hosts - List hosts", None))
        self.graphs_label.setText(_translate("Telebix", "/graphs host - List images graphs of specific host", None))
        self.readmore_label.setText(_translate("Telebix", "<a href=\"https://github.com/warflop/Telebix\">READ MORE ON GITHUB</a>", None))
        self.howtouse_label.setText(_translate("Telebix", "How To Use", None))
        self.howtouse2_label.setText(_translate("Telebix", "2. Fill in all the data in the settings tab to start program", None))
        self.howtouse1_label.setText(_translate("Telebix", "<a href=\"link\">1. Follow these steps to create a bot on Telegram</a>", None))
        self.label_4.setText(_translate("Telebix", "Host:", None))
        self.label_5.setText(_translate("Telebix", "User:", None))
        self.label_6.setText(_translate("Telebix", "Pass:", None))
        self.save_zabbix.setText(_translate("Telebix", "Save", None))
        self.contact.setText(_translate("Telebix", "Contact:", None))
        self.contact_1.setText(_translate("Telebix", "Edvan Oliveira Gomes", None))
        self.contact_email1.setText(_translate("Telebix", "edvanogomes2@gmail.com", None))
        self.license.setText(_translate("Telebix", "License:", None))
        self.gnu_license.setText(_translate("Telebix", "<a href=\"http://www.gnu.org/licenses/gpl.txt\">GNU General Public License v3.0</a>", None))
        self.contact_2.setText(_translate("Telebix", "Jonathas Araujo dos Santos", None))
        self.contact_email2.setText(_translate("Telebix", "jonathas.araujo@live.com", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Telebix", "Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Telebix", "Help", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Telebix", "About", None))

class License(QtGui.QTextEdit):

    def __init__(self,parent = None):
        super(License,self).__init__(parent)
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowMinMaxButtonsHint)
        self.setReadOnly(True)
        self.setWindowTitle('Creating Bots')
        self.setFixedSize(630, 330)
        self.center()
        self.setText(open('SETTINGS','r').read())

    def center(self):

        qr = self.frameGeometry()
        cp = QtGui.QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())
